version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Specify the Python version
python:
  version: 3.10  # Use only major and minor version (e.g., "3.10")

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Use only major and minor version (e.g., "3.10")