version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Specify the Python version
python: "3.10"  # This line is fine

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: 3.10  # Remove quotes around the Python version
