version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Specify the Python version
python:
  version: 3.10  # Use a dictionary with the `version` key

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"  # Use a string for the Python version