version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally, specify the Python version to use
python:
  version: 3.10.12  # Replace with your preferred Python version (e.g., 3.9, 3.10)
build:
  os: ubuntu-22.04
  tools:
    python: "3.10.12"